# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_image'),
        ('recoveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('md5sum', models.CharField(blank=True, max_length=32)),
                ('sha1sum', models.CharField(blank=True, max_length=40)),
                ('sha512', models.CharField(max_length=128)),
                ('build_number', models.IntegerField()),
                ('fingerprint', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoveries.Recovery')),
            ],
        ),
    ]
