# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('md5sum', models.CharField(blank=True, max_length=32)),
                ('sha1sum', models.CharField(blank=True, max_length=40)),
                ('sha512', models.CharField(max_length=128)),
                ('build_number', models.IntegerField()),
                ('fingerprint', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('image', models.FileField(default=b'noimage.png', upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40)),
                ('sha512', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='build',
            name='recovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Recovery'),
        ),
    ]
