# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basepath', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
