# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sha1sum', models.CharField(blank=True, max_length=40)),
                ('sha512', models.CharField(max_length=128)),
            ],
        ),
    ]
