"""empty message

Revision ID: 3e365a3e2ba0
Revises: None
Create Date: 2016-02-27 22:30:00.465307

"""

# revision identifiers, used by Alembic.
revision = '3e365a3e2ba0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('oem', sa.String(), nullable=True),
    sa.Column('wiki', sa.String(), nullable=True),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('build_number', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_number')
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('md5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['build'], ['build.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact')
    op.drop_table('build')
    op.drop_table('device')
    ### end Alembic commands ###
